quattor/template-library-core

pan/types.pan

UUID type is used by different Quattor components. It makes sense to include it into pan/types

included new type_uuid

---

quattor/client/rpms.pan

- required dependency for YUM (or one of its plugin) not listed as an explicit dependency
Fixes an issue found during 15.4.0-rc4 (https://github.com/quattor/release/issues/96) introduced by recent cleanups in `quattor/client\rpms.pan`.

Restore addition python-elementtree on SL5

---

quattor/schema.pan
quattor/types/aquilon.pan
quattor/types/hardware.pan
quattor/types/metadata.pan
quattor/types/system.pan

We've been carrying these in an aquilon branch in the repository up until now, the recent restructuring of the schema forced me to look at integrating this again.

Add missing types required to support aquilon

---

pan/types.pan

Somehow these slipped through my prior testing and were only exposed when running `ncm-metaconfig` unit tests. :disappointed:

Fix problems with is_network_name and related functions

---

pan/types.pan

Permit both in `is_network_name`, fixes the test failures seen in quattor/configuration-modules-core#582

Distinguish between IPv4 and IPv6 networks

---

quattor/types/hardware.pan

Hi,
I'm a new quattor user from T2_BE_IIHE, this is my first pull request, so I apologize beforehand if I'm doing something wrong !
I'd like to make changes to how slots are calculated for hyperthreaded CPUs. 
This merge request just adds a new field to the cpu structure. It will allow us to compute the number of logical cores for CPUs with hyperthreading. It defaults to false.
Cheers
Romain

Add boolean hyperthreading for structure cpu.

---

quattor/types/hardware.pan

This is intended for use with batch systems in order to calculate scaling factors for accurate wall time calculations
I could also see this being useful for other systems such as accounting for storage systems.

Add a benchmark field to the hardware type definition

---

quattor/functions/validation.pan

To be used by components such as filecopy and metaconfig.
See quattor/configuration-modules-core#628

Add function to validate that paths in dict keys are valid files

---

quattor/blockdevices.pan

Depends on https://github.com/quattor/ncm-lib-blockdevices/pull/61

LV: add support for lvmcache in schema

---

pan/legacy.pan
pan/types.pan

Types in here should be collected to be phased out of use.
The first is the infamous non-boolean yesnostring used by several component with different names.

Add new template for legacy types

---

quattor/types/hardware.pan

Following on from #94 and related to quattor/template-library-standard#66, it would be nice to be able to record the physical threadcount of CPUs.

Allow thread count of CPU to be specified

---

quattor/client/rpms.pan

Cleanup simplifying Quattor client configuration.
Can be seen as a final contribution to #65.
Fixes #84.

quattor/client/rpms: use pkg_repl() to configure RPMs

---

pan/legacy.pan

For the 16.8 cycle I plan to migrate as many properties of as many components as possible from using `legacy_binary_affirmation_string` to `transitional_yes_no_true_false`, then migrate them to `boolean` in a following release cycle.

Add a transitional type to allow components to migrate to real booleans

---

quattor/aii/opennebula/default.pan

Replace undef with null to allow the schema to apply defaults as the comment suggests
This fixes the test errors seen in #110, #120 and #121.
Also did some re-factoring, because the code made me feel sad.

aii-opennebula: Fix default values of global variables

---

pan/types.pan

They are not valid, but we have allowed them with a deprecation warning since the 15.8 release.
Closes #78.

Throw error if short hostname is used as a network_name

---

quattor/types/hardware.pan

Preferred here should not be mandatory.
I also cannot see anywhere where this value is used

Preferred should not be mandatory

---

quattor/functions/filesystem.pan

Originally, `partitions_add` was only able to configure the size of a partition. The interface has been improved to received a dict of partition attributes rather than a number (partition size). For backward compatibility, the previous interface is still valid.
Partly fixes #72 (the complete fix requires the complementary improvement in template-library-core).

Improved interface for partitions_add()

---

quattor/client/pan_compiler.pan

This PR also make the default site-customizable through `PANC_DEFAULT_VERSION`.
10.3-1 contains an important fix related to possible modification of a global variable from a foreach in a DML (attached to another variable). It would be important IMO to set it as the new panc baseline.
Tests made on the template library showed no problems triggered by this fix.
As this is not urgent, I propose to set this new baseline in 16.12.

Upgrade default panc version to 10.3-1

---

quattor/types/hardware.pan

This is the next step in deprecation towards removal and will ensure that only sites actively setting the parameter will receive deprecation warnings.

Make CPU hyperthreading optional and remove default value

---

pan/types.pan

ARGV does not make sense outside of a function.
Bug was introduced in #135

Use SELF in validation

---

quattor/blockdevices.pan

Support for vxvm blockdevices was added via quattor/ncm-lib-blockdevices#60 but
the corresponding template change to blockdevices.pan was overlooked.

Support vxvm blockdevices

---

pan/types.pan
quattor/types/annotation.pan
quattor/types/system.pan

Related to #142 (implements validation of OS architecture).
Tagged as backwards incompatible as this will start to validate previously free-form fields.

Add CPU architecture type definition

---

pan/types.pan
quattor/types/annotation.pan
quattor/types/aquilon.pan
quattor/types/os.pan
quattor/types/system.pan

We have systems that consume host profiles and need to extract information about the operating system, currently this is done with some nasty regex magic looking at values in locations such as `/system/aii/nbp/pxelinux/kernel` or in one case munging the contents of `/software/components/filecopy/services/{/etc/motd}/config`.
Since the actual information is present in aquilon and during compilation it can be trivially added to the profile.
The reference to OS in the schema at `/system/archetype/os` (defined in quattor/types/aquilon.pan) has been redefined to model the values (name and version) as managed by the aquilon broker.
The current plan is to populate `/system/os` from the `OS_VERSION_PARAMS` as used in template-library-standard, but this could in future be migrated to operating on …

Add structures to model operating system information

---

quattor/types/system.pan

The purpose of these fields is unknown and apparently unused.
Resolves #145.
Backwards incompatible for any hypothetical sites who may use it.

Remove /system/oldnames from schema

---

quattor/blockdevices.pan

Was introduced in https://github.com/quattor/ncm-lib-blockdevices/pull/40
Requires https://github.com/quattor/ncm-lib-blockdevices/pull/73

blockdevices: add validation check configuration to physical devices

---

quattor/functions/network.pan

Fixes #148 #149
Backwards incompatible due to removal of get_subnet_params function #

quattor/functions/network: cleanup and removal of get_subnet_params function

---

quattor/functions/network.pan

Reimplement `get_subnet_params()` removed in #150 based on new `ip_in_network()` (#151). This function is used in several sites (GRIF at least) to configure the network parameters (see https://github.com/quattor/template-library-core/pull/150#issuecomment-287303037).
The old function was written before bitwise operations were implemented in panc and for this reason the subnet was a regexp rather than a real subnet. The new function tries to convert this regexp to a subnet if it is a simple one and print a deprecation warning. If it cannot be converted, an error is raised by `ip_in_network()` because this is not a valid IPv4 address. A typical regexp properly converted is `134\.158\.72\.*'. One too complex is `134\.158\.7(2|3)\.*'.
*Note1: the deprecation warning is not displayed if …

functions/network.pan: readd a modernized get_subnet_params()

---

quattor/functions/network.pan

The update to the network component made backwards incompatible changes to the schema, in this case changing onboot from a string to a boolean. We should therefore not inject broken values into site configuration.

Fix usage of onboot in copy_network_params function

---

quattor/client/rpms.pan

- Useful when Quattor is used to manage a VM image rather than a machine (in this case `ncm-ncd` is generally run manually and the profile name doesn't match a host name, making cdp notification useless)

client/rpms: allow to disable ncm-cdispd/cdp-listend installation

---

quattor/types/hardware.pan
quattor/types/sensors.pan

We use this at RAL to configure per-model thresholds for automatic shutdown.
The implementation details of how this data is used is left up to end users, including the interpretation of thresholds, units etc.

schema: Add structure for modelling hardware sensors

---

pan/types.pan

To be used in code that handles capabilities, e.g quattor/configuration-modules-core#1212.

pan types: Add type to model Linux capabilities

---

quattor/types/aquilon.pan
quattor/types/system.pan

The resources structure is used by the broker to model children of a host
(or cluster) for example virtual machines on a hypervisor.

schema: Add resources to system structure

---

quattor/types/hardware.pan

Knowing the amount of RAM that a GPU has is very useful for making deployment and scheduling decisions, so provide the ability for it to be modelled.

Allow RAM to be modelled on GPU cards

---

quattor/types/aquilon.pan

These changes were included as part of #142, but were not necessary for that use-case. The impact of these changes was underestimated and as the new types appear to be unused in the community the change should be reverted ASAP.
Fixes #179.
Fixes quattor/aquilon#93.

Revert /system/archetype/os changes

---

pan/functions.pan

- domain_from_object(): remove the required argument for defining the default domain (argument use is now deprecated)
- fullname_from_object(): function deprecated (just return OBJECT)
It's already 10 years than the object template name is required to be the host FQDN! Time for cleanup! In particular, requiring a default domain makes no sense has it will never be used. A deprecation warning is issued if still using the old forms that are normally easy to solve as the call to this function used to be in one place (in SCDB, `global_variables.pan`)

pan/functions: cleanup and remove support from profile_xxx

---

quattor/types/aquilon.pan
quattor/types/aquilon/hardware.pan
quattor/types/aquilon/system.pan
quattor/types/hardware.pan
quattor/types/system.pan

As explained in https://github.com/quattor/aquilon/issues/90, current schema is not consistent with plenary templates generated by Aquilon (1.12.58). This PR reconciles them, preserving backward compatibility
This PR also improves the schema layout by factoring out of the base file hardware resources specific to Aquilon. And all the properties mandatory in the Aquilon DB and passed by the broker into the generated templates have been defined as mandatory.

Schema fixes required for Aquilon support

---

pan/types.pan

- `[:upper:]` replaced by `[A-Z]`
Fixes #186

pan/types: fix incorrect regexp for linux_capability

---

test_templates.sh

Avoids issues with duplicate type definitions from multi-version schema which have been causing tests to fail on this repository.

test_templates: Use a single version of schema for ceph and ssh

---

quattor/types/aquilon/hardware.pan

In previous change, several location-related attributes were made
mandatory as they are required for a machine object. But they
are not for a cluster, with the consequence that they may not be defined
for the virtual machines hosted by the cluster.

Aquilon schema: location attribute requirements relaxed

---

quattor/functions/validation.pan

In some cases, we need to be able to check a username received as
parameter, this allows it by providing a new valid_user_name function
that checks that the username received as parameter is a valid one,
i.e. comprised only of alphanumeric characters, plus a few
special ones: .+:-

Add a valid_user type

---

quattor/types/aquilon/system.pan

A new entitlement system is being added to the Aquilon broker. It will
allow to set entitlements of a given type (for instance, 'login' or
'root') and enable them by host, cluster, personality, archetype or
Grn/EonID.
These new entitlements need to be stored to be picked up by the
templates in order to act on them, and this is why the
structure_entitlements is being added: we will now have in the
structure_system_aquilon structure an "entitlements" dictionary that
will use the entitlements type as key, and a structure_entitlements
as value. In there, we will find entitlements per-EonID or per-user.
In the later case, the user type (also being added to the broker)
will also be mentioned (as to, for instance, insure some activities
are only being entitled for system users).

types: aquilon: add new structure_entitlements in the system parameters

---

quattor/filesystems.pan

Extend the validation of the type resource in structure_filesystem
to allow "auto" to be used. This is useful for fstab entries which have
been created outside Quattor, and the fstype may not be known.
According to mount(8) the order in which fs types are tried can be
controlled using /etc/filesystems.

Add auto as a valid filesystem type

---

pan/types.pan

This arose while reviewing quattor/configuration-modules-core#1410.
In an ideal world of course search paths would be modelled as lists of absolute paths, but this should be useful nonetheless.
Based on #197.

pan/types: Add string type for search paths

---

pan/types.pan

As suggested by @gombasg, just parse it numerically to fit in the interval [0,07777].
@ned21 as requested in quattor/configuration-modules-core#1396

Add string type for an octal mode/mask

---

quattor/types/hardware.pan

Add a new attribute to the hardware structure to allow the configuration
of optional hardware settings, such as disk encryption.

hardware types: add options structure

---

quattor/functions/hardware.pan

Much of the configuration of our compute systems relies on knowing both the number of cores and threads available on any given host and as such a number of home-grown "quick fixes" have developed for obtaining this information. This is an attempt to provide the functionality upstream with the hope of removing out local kludges in future.

quattor/functions/hardware: Provide function to get max_threads for all CPUs

---

quattor/functions/hardware.pan

i.e. the total of all banks.
We see a lot of user code that uses `value('/hardware/ram/0/size')` as a shortcut, but this falls apart when NUMA configurations have been modelled.
This is based on code in `template-library-standard/os/kernel_version_arch.pan`.

quattor/functions/hardware: Provide function to get total system RAM

---

quattor/client/pan_compiler.pan

Language features such as choice (10.4) and relative prefix statements (10.7) are now commonly used across the codebase.

panc 10.7 is now the minimum supported compiler

---

quattor/aii/ks/variants/el8.pan
quattor/client/rpms.pan

- Add the missing template for AII KS
- Ensure that the `ncm-spma` version used is the one configured, if the default version was changed (.e.g. for testing)

El8 support

---

pan/legacy.pan

This is aimed at solving the migration path for quattor/configuration-modules-core#1464 in a backwards compatible way.

Add a transitional type for strings being migrated to lists of strings

---

pan/types.pan

Some configurations require comma-separated email addresses. This type is useful to validate those.
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE APACHE LICENSE, V.2.0. YOU MAY OBTAIN A COPY OF THE LICENSE AT https://www.apache.org/licenses/LICENSE-2.0.
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; …

New type for strings which represent lists of email addresses

---

quattor/functions/filesystem.pan

New function, lvo_add. This is to replace lvs_add function which only sets size when adding of logical volumes to a volume group. with this function, you can provide list of lv options to add, raid_type is one of them. Creating raid through LVM is now possible, therefore this function provides support for setting the type for logical volumes.
fixes https://github.com/quattor/template-library-standard/issues/150

New function lvo_add to add lv options

---

components/ntpd/schema.pan

The step value is represented in seconds.
See tinker definition in https://www.ntp.org/documentation/4.2.8-series/miscopt/

Fix type of ntpd_tinker_options/step #219

---

test_templates.sh

Kibana and SLURM were made multiversion in the last release, but this step was forgotten.

Update list of multiversion schema

---

quattor/types/hardware.pan

bootmode with a choice of "uefi" or "bios" added to the bios subtree

add bootmode option to provide support for uefi

---

quattor/types/hardware.pan

HEPScore23 started to replace HS06 from April 2023 onward and is now the primary benchmark used by WLCG.
See also: https://w3.hepix.org/benchmarking.html

types/hardware: Add HEPScore23 and deprecate HS06

---

quattor/aii/config.pan
quattor/aii/rpms.pan
quattor/aii/schema.pan

Restore the AII templates deleted by a failure of the releaser script during the RC2 build.
This reverts commit 0692641c6c2ceb63f725d55964f4c36809f749d0.

Revert "AII templates for tag 24.10.0-rc2"

---

quattor/functions/network.pan

- Required for `nmstate` to work properly for unconfigured interfaces
I mark this PR as backward incompatible as it changes the resulting profile compared to previous version but I think it fixes something that was wrong but working with initscripts (because they don't care about interfaces not enabled on boot).

quattor/functions/network copy_network_params: bootproto=none for unconfigured interfaces

---

quattor/functions/network.pan

By default, `get_subnet_params()` return value is compatible with the interface schema (`/system/network/interfaces`). Thus the subnet parameter which is part of the `get_subnet_params()` input is removed. Sometimes, it may be desirable to get it returned. To make it possible, a third optional argument has been added (boolean). When `true`, the subnet is return. Default is unchanged (subnet not returned to be compatible with the interface schema).

quattor/functions/network get_subnet_params: allow to return subnet

---

quattor/physdevices.pan
quattor/types/hardware.pan

The `boss-n1` card in template-library-standard already does, which currently makes it unusable.

physdevices: RAID controllers can have PCI details
