quattor/types/component.pan
Related to quattor/configuration-modules-core#553
=> Deprecate shipping of component code in profiles

pan/types.pan
Fixes #66
Tested and seems to work as desired!
=> is_fqdn: only match FULLY QUALIFIED domain names

pan/types.pan
Spotted while trying to build RC1.
=> Fix typo in function name

test_templates.sh
To replace the hardcoded test in jenkins
=> Add script as primitive template test

quattor/blockdevices.pan
Comes with PR https://github.com/quattor/ncm-lib-blockdevices/pull/56
=> Blockdevices: add metadata option to md devs

quattor/types/component.pan
=> Remove component code parameter

test_templates.sh
Fixes failing jenkins unittests
=> Fix test_templates script

pan/units.pan
As discussed in quattor/template-library-grid#180.
=> [pan/units] added more binary constants

pan/types.pan, quattor/functions/validation.pan
Factors out inner logic valid_absolute_file_paths into new is_absolute_file_path function.
Resolves #116.
=> Introduce an absolute_file_path type

quattor/types/aii.pan
added value for https://github.com/quattor/aii/pull/172
=> aii schema: add protected option

quattor/types/system.pan
Following the proposition of @ned21 (https://github.com/quattor/template-library-core/issues/59#issuecomment-252009328)
=> Make monitoring optional

quattor/functions/package.pan
Syntax of the annotation incorrect, I have a meeting, I'll tro fix it when I am done with it.
=> functions/package: add a comment/description to pkg_compare_version funciton

.travis.yml, pan/functions.pan, travis-build
Run panlint against files changed in each PR.
Refactors pan/functions in order to test and then satisfy the linter.
=> Test basic pan linting tests

pan/types.pan
=> Add valid_interface type

quattor/types/metadata.pan
Add some documentation about the metadata tree as requested in #142
=> Metadata annotation

quattor/blockdevices.pan
=> blockdevices schema: add support for esp partition flag

quattor/functions/network.pan
=> quattor/functions/network: add ip_in_network function

quattor/functions/validation.pan, quattor/types/hardware.pan
We use these at UGent for maintaining IB HCA's.
=> types/hardware: Add Infiniband definitions.

quattor/types/annotation.pan, quattor/types/hardware.pan
Cleaned up the documentation and added 3 fields used at UGent
=> annotation: cleanup and add support, procured and site fields

quattor/types/hardware.pan
Adds a very basic hardware support for GPUs
=> Add basic support for GPUs

quattor/aii/opennebula/default.pan, quattor/aii/opennebula/functions.pan, quattor/aii/opennebula/rpms.pan, quattor/aii/opennebula/schema.pan
These are provided by the component, but not auto-copied during the release cycle, which has been breaking things.
=> Add missing aii schema for opennebula

quattor/cluster/base.pan, quattor/cluster/schema.pan, quattor/schema.pan, quattor/types/aquilon.pan, quattor/types/hardware.pan, quattor/types/software.pan, quattor/types/system.pan
=> schema: Add support for aquilon clusters

quattor/functions/network.pan
Add two new functions to convert a prefix length to netmask and vice versa.
=> quattor: functions : network: add subnet_prefix_to_mask

quattor/functions/filesystem.pan
Code clean-up makes use of pan 10.7 features.
Will need https://github.com/quattor/scdb/pull/46 to be merged to pass Travis tests.
=> functions filesystem: partitions_add: fix number of required arguments bug

pan/strings.pan, pan/types.pan, quattor/types/sensors.pan
* Non-empty string
* String without any white-space
* String without leading or trailing white-space
=> Define some simple string types to build upon

.travis-scripts/indent, .travis.yml
We had a work-experience student again over the summer who finished work on an indentation checker/re-formatter for Pan code (and potentially other languages, but let's not push it).
This adds it as a Travis test to see how useful it might be.
=> Run indentation check against modified pan files

quattor/client/pan_compiler.pan, quattor/types/hardware.pan, quattor/types/licence.pan, quattor/types/license.pan, quattor/types/site.pan, quattor/types/system.pan
Also fixes type of `bmc` console which was mistakenly set to `structure_dpc_console`.
=> types: hardware and system additions for bios and site related changes

pan/types.pan
Addresses some of the issues flagged by tests (but that were not part of) #196.
=> pan/types: Cleanup style - lint, indentation, wrapping

quattor/physdevices.pan
=> Add NVMe to block device interface types

.github/workflows/syntax.yaml, .github/workflows/test_templates.yaml, components/ceph/config.pan, test_templates.sh
=> Use github actions for tests

.github/workflows/syntax.yaml
Otherwise we need to keep chasing it.
=> Don't specific minor Python 3 version for checks

quattor/blockdevices.pan
=> Cleanup blockdevices template

quattor/filesystems.pan
=> Cleanup filesystems template

.github/workflows/test_templates.yaml
This ensures correct dependencies are present.
Also bump checkout action.
=> workflows: Run template testing action on our own container image

pan/types.pan
=> pan/types: Add type for crypt format password hashes

quattor/functions/hardware.pan, quattor/types/hardware.pan
Fix the underlying issues mentioned by @maxeem in quattor/template-library-standard#161.
=> hardware: Fix bugs in max threads calculation and validate schema property

quattor/aii/ks/variants/el9.pan
Changes that were needed in the EL9 variant at IJCLab...
=> AII KS variant for EL9: fix required packages and Anaconda version

.ci-scripts/indent, .ci-scripts/panlint
Prevent errors that may occur if a file is deleted as there will be an attempt to check it.
* Tested successfully on the `template-library-openstack` repository
=> CI scripts (panlint/indent): exclude deleted files

quattor/server/rpms.pan
=> quattor/server/rpms: fix DHCP client RPM for EL9
